spring:
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        ddl-auto: create


logging:
  level:
    dev.fastcampus: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace