spring:
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:~/test

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        ddl-auto: update

logging:
  level:
    dev.fastcampus: debug
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace